Issue 6. Add tootip
stormpython/heatmap pull request #41
Opened 2016-09-15 19:41 UTC by nmqhoan

We updated the code based on your indications in PR #38 
 close #6

2016-09-16 15:57 UTC, stormpython commented
@nmqhoan thanks for the new pr. I will check this out over the weekend. But just out of curiousity, where is d3.tip used? I just did a cursory look through and couldn't find where it was being implemented.

2016-09-16 16:39 UTC, tuhp commented
Hi @stormpython ,
This is redundant file. It does not use anywhere in the plugin. It should be removed. 
Thanks.

2016-09-16 16:45 UTC, nmqhoan commented
@stormpython, thanks for reviewing the code. I removed the d3.tip.js and committed.

2016-09-20 18:26 UTC, stormpython commented on public/heatmap_tooltip.css
> +  background-color: #d3d3d3;
I think this can be changed to match the style in Kibana, which is:
fadeout(@gray-darker, 7%);
gray-darker: #222222

2016-09-20 18:28 UTC, stormpython commented on public/tooltip_directive.js
> +var d3 = require("d3");
I am guessing this file should be removed?

2016-09-20 18:28 UTC, stormpython commented on public/vis/components/axis/axis.js
>        text.exit().remove();
why was the space here removed?

2016-09-20 18:28 UTC, stormpython commented on public/vis/components/elements/text.js
>          text.exit().remove();
why was the space above removed?

2016-09-20 18:29 UTC, stormpython commented on public/vis/index.js
>        layout.attr({
why was the space above removed?

2016-09-20 18:29 UTC, stormpython commented on public/lib/heatmap_controller.js
> +              if(key.toUpperCase() === 'ROW')
there should be a space between if and (

2016-09-20 18:30 UTC, stormpython commented on public/lib/heatmap_controller.js
> +              if(key.toUpperCase() === 'ROW')
Same goes for the if statement below.

2016-09-20 18:30 UTC, stormpython commented on public/lib/heatmap_controller.js
> +              if(key.toUpperCase() === 'ROW')
They are also missing curly braces.

2016-09-20 18:31 UTC, stormpython requested changes
Aside from a few syntax things, this pr looks good.

2016-09-26 16:43 UTC, stormpython commented
LGTM!

2016-09-26 16:44 UTC, stormpython approved these changes

2016-09-26 16:44 UTC, merged